### ISSUE TITLE
Exception when space characters are included

### ISSUE THREAD

**Issue by lennybakkalian** [nabildridi/SpringBootGenericPagingFilteringForPrimengTable#9]
When searching for something with a space in it, the following Exception is thrown

```
2020-12-10 23:42:26.994 ERROR 30620 --- [nio-8000-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is cz.jirutka.rsql.parser.RSQLParserException: cz.jirutka.rsql.parser.ParseException: Encountered " <UNRESERVED_STR> "d* "" at line 1, column 20.
Was expecting one of:
    <EOF> 
    <AND> ...
    <OR> ...
    ] with root cause

cz.jirutka.rsql.parser.ParseException: Encountered " <UNRESERVED_STR> "d* "" at line 1, column 20.
Was expecting one of:
    <EOF> 
    <AND> ...
    <OR> ...
    
	at cz.jirutka.rsql.parser.Parser.generateParseException(Parser.java:384) ~[rsql-parser-2.1.0.jar:2.1.0]
	at cz.jirutka.rsql.parser.Parser.jj_consume_token(Parser.java:322) ~[rsql-parser-2.1.0.jar:2.1.0]
	at cz.jirutka.rsql.parser.Parser.Input(Parser.java:39) ~[rsql-parser-2.1.0.jar:2.1.0]
	at cz.jirutka.rsql.parser.RSQLParser.parse(RSQLParser.java:120) ~[rsql-parser-2.1.0.jar:2.1.0]
	at io.github.perplexhub.rsql.RSQLJPASupport$1.toPredicate(RSQLJPASupport.java:89) ~[rsql-jpa-5.0.6.jar:na]
	at org.springframework.data.jpa.domain.SpecificationComposition.toPredicate(SpecificationComposition.java:60) ~[spring-data-jpa-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at ........
```

**Comment by nabildridi** [comment]
Fixed
